# version: '3.9'
services:
  bookstore-api:
    build:
      context: ./
      dockerfile: apps/bookstore-api/Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      - PORT=3000 #expose port 3000
      - HOST=0.0.0.0 #bind to all interface so it would be accessible from outside the container
    working_dir: /usr/src/app
    command: sh -c "npx nx run @bookstore/bookstore-api:migrate && npx nx run @bookstore/bookstore-api:seed && nx serve bookstore-api"
    # command: nx serve bookstore-api
    # command: node apps/bookstore-api/dist/main.js
  bookstore-fe:
    build:
      context: ./
      dockerfile: apps/bookstore-fe/Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4200:4200
    environment:
      - PORT=4200 #expose port 3000
      - HOST=0.0.0.0 #bind to all interface so it would be accessible from outside the container
    working_dir: /usr/src/app
    command: sh -c "nx sync && nx serve bookstore-fe"
# networks:
#   app-network:
#     driver: bridge
