version: '3.9'
services:
  bookstore-api:
    build: ./apps/bookstore-api
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - PORT=3000 #expose port 3000
      - HOST=0.0.0.0 #bind to all interface so it would be accessible from outside the container
    networks:
      - app-network
    working_dir: /usr/src/app
    command: nx serve bookstore-api
networks:
  app-network:
    driver: bridge
